// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izbltsftwemdkwhnptcj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6Ymx0c2Z0d2VtZGt3aG5wdGNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MzI2MTgsImV4cCI6MjA2NjUwODYxOH0.hAv-fK_Qu41Is6Z1y4cPknsMy95A3q4DiJqhpv2OnTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);